nodeLinker: node-modules

npmAuditRegistry: "https://registry.npmjs.org"

npmAlwaysAuth: false

npmAuthToken: "${NPM_AUTH_TOKEN}"

npmPublishAccess: public

yarnPath: .yarn/releases/yarn-3.7.0.cjs

enableColors: true



